server:
  port: 8761

spring:
  application:
    name: discovery-server
  config:
    import: "optional:configserver:${CONFIG_URI:http://localhost:8888}"


eureka:
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME:discovery-server}
    instance-id: ${spring.application.name}:${HOSTNAME}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

